"""dictionary item table initialized

Revision ID: ab27295f59cd
Revises:
Create Date: 2024-04-15 00:22:03.267941

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "ab27295f59cd"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
