repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort src/
        language: system
        types: [python]
        pass_filenames: false

      - id: black
        name: black
        entry: black src/
        language: system
        types: [python]
        pass_filenames: false

      - id: flake8
        name: flake8
        entry: flake8 src/
        language: system
        types: [python]
        pass_filenames: false
      
      - id: tests
        name: tests
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
